### ISSUE TITLE
Should Auxiliary channels require component field?

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mt_metadata#117]
Encountering failures in `aurora` [PR239](https://github.com/simpeg/aurora/pull/239#top) in Parkfield tests.  This originally looked like an NCEDC data access problem, but I have confirmed that it is not - at least not if using `obspy` v1.4.

An exception is raised in run.py

If I modify:
```
if channel_obj.component is None:
            msg = "component cannot be empty"
            self.logger.error(msg)
            raise ValueError(msg)
```

to:
```
if channel_obj.component is None:
            if not isinstance(channel_obj, Auxiliary):
                msg = "component cannot be empty"
                self.logger.error(msg)
                raise ValueError(msg)
```
I get the Parkfield tests passing.

Two questions:
1. Should an Auxiliary channel be forced to have a component ?
2. Why are there channels of type "Auxiliary" showing up in the parkfield tests when the only requested channels are Electric and Magnetic? 

Some more details in Aurora issue 159 comments Dec 29, 2022.

**Comment by kujaku11** [comment]
@kkappler I think that this makes sense with the newer backend that has a single metadata object for the channels.  When the channel is initialized it has a default auxiliary channel with an empty component, seems like somewhere there are empty channels.  Do you have the full traceback?
