### ISSUE TITLE
Logger Error when importing mt_metadata

### ISSUE THREAD

**Issue by kujaku11** [kujaku11/mt_metadata#13]
Get a LoggerError when importing mt_metadata if another process is running.  This makes the logger enter an crazy loop.  Probably has something to do with rotating file handler.

**Comment by kujaku11** [comment]
This error occur when there are multiple python processes are running and accessing the same log file.  The log file is set as a rotating handler, so once the logger hits a memory threshold a new logger file should be written.  However, since there are 2 or more processes accessing the same file the permission to close the current log file and open a new one gets messed up and you get an error with a massive traceback.  

This is mainly a windows problem I think, or so I've read, but should be dealt with either way.  

Other people have had this issue

[Example 1](https://stackoverflow.com/questions/26167873/python-logging-with-multiprocessing-in-windows)

[logging cookbook](https://docs.python.org/3/howto/logging-cookbook.html)

[example solution](https://pypi.org/project/concurrent-log-handler/)

This is above my experience, so any help is gratefully accepted.

**Comment by kkappler** [comment]
This should be fixed.  Closing for now.
Also, default logging level now set to INFO rather than DEBUG
