### ISSUE TITLE
Z-file headers

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mt_metadata#144]
Now that z-files are being written successfully by the TF class there are a few things to tune before we can use these tools routinely

- [x] In the old emtf z file, the processing recipe is written on line 3, in the TF output line 3 is blank
- [x] In the old emtf z file the station name is prefaced by the text string "Station:"  on line 4
- [x] In the old emtf z file, the channel numbering was always contiguous, in TF output the channel numbering is fixed with Hz always being channel 3
- [x] Fortran EMTF files on SPUD have a space between the header and data
- [x] In the TF output, the azimuths and tilts are not being extracted from the run object, only zeros are showing up in the output file
- [x] In the old emtf z file, the indexing of decimation levels starts at 1, in the TF output it starts from 0
- [x] The frequency band integer identifiers are all 0.0 in the TF output, these need to be set to their correct integer values
- [x] The sampling frequency values are all 0.0 in the TF output, these need to be set to their correct floating point values
- [x] In the old emtf z file, TF numbers were formatted with 0 in the first position, in the TF output the first position is non-zero 

We may want to consider using the `fortranformat` package for floating point output.

![z_files_comparison_29May2023](https://github.com/kujaku11/mt_metadata/assets/1154939/c2cbb10f-d033-434a-b354-19cbcff14915)

**Comment by kkappler** [comment]
@kujaku11 Let's review this list after you get back June 9

**Comment by kujaku11** [comment]
@kkappler With PR #159 the header information should be populated from a `TF` object.  However, frequency bands and number of sample used are not. That is specific information that is currently not passed to `TF`.  It would be nice to pass that information, not sure where to put it at the moment.  Could be an attribute of `Station.transfer_function`. 

Nevertheless, the header information of the z-file is being populated from `TF`.

**Comment by kkappler** [comment]
This is pretty much there.  The only remaining thing is for someone who uses z-files in their workflow to test them out.
![image](https://github.com/kujaku11/mt_metadata/assets/1154939/4330a993-0ba3-45c4-9d35-301b6d499661)
