### ISSUE TITLE
time and frequency axes are permuted in FC

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mt_metadata#148]
![image](https://github.com/kujaku11/mt_metadata/assets/1154939/a4b3a52b-12d6-457f-bbcf-603a23602982)
These should be the other way around.

**Comment by kujaku11** [comment]
@kkappler Not sure where the transpose is coming from, could you provide an example cause the tests seem to work fine.

**Comment by kkappler** [comment]
This is now fixed - thanks @kujaku11
