### ISSUE TITLE
Tests failing when nationalmap not responding to requests

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mt_metadata#164]
The tests need to access some URLs such as this one:

> https://epqs.nationalmap.gov/v1/json?x=-110.44&y=44.631&units=Meters&wkid=4326&includeDate=False

But this is not always accessible.   The inability to connect is handled, but the return value (0.0) is not expected and this causes 7 other tests to fail on assertion error.

**Comment by kujaku11** [comment]
Changed the default value in reading transfer function file `get_elevation` to False and updated tests in PR #191.
