### ISSUE TITLE
Update broke test_issue_139 in aurora

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mt_metadata#190]
test_issue_139 was passing, but after pull latest mt_metadata get:

>======================================================================
FAIL: test_tf_read_and_write (__main__.TestZFileReadWrite)
Checks that an ingested z-file is written back out the same
----------------------------------------------------------------------Traceback (most recent call last):
  File "/home/kkappler/software/irismt/aurora/tests/io/test_issue_139.py", line 79, in test_tf_read_and_write
    assert filecmp.cmp(self.zrr_file_base, out_file_path)
AssertionError----------------------------------------------------------------------
Ran 2 tests in 4.785s

I'm looking into it -- this is a placeholder and a reminder

**Comment by kkappler** [comment]
It looks like the conjugate of Inverse Coherent Signal Power Matrix is now being output from a test that reads the z_file and then rewrites it

![image](https://github.com/kujaku11/mt_metadata/assets/1154939/2c778913-c882-48ad-8d3d-fb5f5be57d23)

Probably that test should be moved into mt_metadata

**Comment by kkappler** [comment]
@kujaku11 I added a test that the zmm in TF_ZMM can be written to file (which is not passing) -- fails with error:
>Traceback (most recent call last):
  File "/home/kkappler/software/pycharm-community-2023.1/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/kkappler/software/irismt/mt_metadata/mt_metadata/transfer_functions/io/zfiles/zmm.py", line 588, in write
    c_in_name = self.channel_nomenclature[c_in]
KeyError: 'hx'

Test is on branch `fix_issue_190`

Can you PTAL, and once the writer is behaving we should be able to see if there really is an issue with conjugate values.

**Comment by kujaku11** [comment]
Fixed on PR #192
