### ISSUE TITLE
Create metadata for EMTF XML

### ISSUE THREAD

**Issue by kujaku11** [kujaku11/mt_metadata#2]
Create the metadata standards for EMTF XML data and translation into a more standard version similar to the time series metadata.

**Comment by kkappler** [comment]
This will involve 
@kkappler to generate the data that goes into the container from aurora
@kujaku11 to formulate the datastructure

The pipeline from EMTF_XML to IRIS DB is already done with a pipeline that is fairly robust.  We just need to tap this pipeline.  @tronan @anna can help with any kinks in the pipeline.

@kujaku11 : to provide karl with an example file ready for "data populating", and then we can decide what the tool looks like that actually inserts the data

Aurora will output an MTObject (from MTpy) and this general container can translate into EMTF_XML, EDI, etc.
