### ISSUE TITLE
import of ChannelResponseFilter fails

### ISSUE THREAD

**Issue by CedricPatzer** [kujaku11/mt_metadata#201]
Hei,
I tried to import some function from fiters module and get the follwoing import error:
ImportError: cannot import name 'ChannelResponseFilter' from 'mt_metadata.timeseries.filters'
Downgrading from version 0.3.4 to 0.3.3 fixed issue. 
Regards

**Comment by kujaku11** [comment]
@CedricPatzer In the new version the `ChannelResponseFilter` is now named `ChannelResponse`.  Should have added a deprecation notice.
