### ISSUE TITLE
file in use?

### ISSUE THREAD

**Issue by lheagy** [kujaku11/mt_metadata#21]
Is the [util.py](/util.py) file being used for something? or is this one we can clean out?

**Comment by kkappler** [comment]
I just deleted it and pushed ... some old file from when we were just starting the repo and not needed.

**Comment by kkappler** [comment]
@lheagy : for the record, I deleted on the branch "stationxml_filters"

**Comment by lheagy** [comment]
Thanks @kkappler, we can close this when #19 is merged in
