### ISSUE TITLE
Stop Loading Example Data from mth5_test_data

### ISSUE THREAD

**Issue by kujaku11** [kujaku11/mt_metadata#24]
Need to remove any dependencies on MTH5 and probably can remove dependencies on the mth5_test_data, the XML files are small enough to pack with mt_metadata.  

Suggest putting any example XML files into the mt_metadata/data folder and load all files from there.  This should make the tests run easier and remove dependencies on too many external packages.

**Comment by kkappler** [comment]
Lets do the same with calibration files

**Comment by kkappler** [comment]
all tests are loading from the mt_metadata/data folder
