### ISSUE TITLE
Get all tests in mt_metadata passing

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mt_metadata#25]

**Comment by kujaku11** [comment]
All tests pass for now.  I will close this once a pull request is completed.

**Comment by kujaku11** [comment]
Famous last words.  All the test pass on my local machine, but now they don't pass on the GitTests.  It looks like it has to do with Obspy and how its instantiated.  

@kkappler  or @lheagy any chance one of you can see what the difference is between the tests that passed a few days ago and the most recent ones that didn't pass?

**Comment by kujaku11** [comment]
Must have been the GitTest environment, everything is good now.
