### ISSUE TITLE
two readmes

### ISSUE THREAD

**Issue by lheagy** [kujaku11/mt_metadata#28]
It seems we have a readme both in md and rst. It can be a bit annoying to maintain two. Do you have  a preference for either? In the SimPEG repo, we stuck with the `rst` file as it was the same as the rest of the docs, but it doesn't make much difference, sphinx can handle both. So just suggesting we have one rather than two :-)

**Comment by kujaku11** [comment]
I saw that too.  I put everything in the .md file, and removed the .rst.

**Comment by kkappler** [comment]
there is only one readme now
