### ISSUE TITLE
Create documentation for each standard

### ISSUE THREAD

**Issue by kujaku11** [kujaku11/mt_metadata#3]
Create sphinx documentation for each standard

**Comment by kkappler** [comment]
1a). Review __init__ considerations for filters
Karl is often declaring ivars under the __init__() method of the filter instance classes, but these seem to be handled inside the standard jsons.  Review the logic on this and describe it in a paragraph.  
1b)  I.e. if the instance attributes are listed in the json and not the class what is the best way to make the documentation clearly show the instance variables to the users?

2. Write a paragraph describing the Filter philosopy, what is working, what may fail ... e.g. 
The filters are all instances of a base class that have several properties common to all filters such as gain, input units, output units.  This class is then extended for each type of filter we may encounter.  The types of filters addressed are 
{list them here}.  The core method of each filter is the complex_response()  which takes as input a frequency or a numpy array of frequencies and returns a complex number which represents the filter output factor.  This is H(f) such that the output phasor = H(f) * input phasor.  ** TBC**

**Comment by kujaku11** [comment]
Calling the documentation adequate.
