### ISSUE TITLE
decide if scale factors module is to be included

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mt_metadata#30]
@kujaku11 
Should we create a module with things like
degrees_to_radians
radians_to_degrees
mV_per_km_to_V_per_meter
V_per_meter_to_mV_per_km
etc?
It's a bit hokey but I think makes the code more readable and makes the codes less error prone by centralizing all the scale factors to one place where are imported from

maybe put in mt_metadata.util ?

**Comment by kujaku11** [comment]
@kkappler There should probably be something like this that accepts all acceptable units and conversions.  Maybe using an external package like [Pint](https://pint.readthedocs.io/en/stable/) could be a solution.

**Comment by kkappler** [comment]
Units get encountered in Channel and in the filters (stages).  Let's put a list of all the encountered units somewhere

Notionally, we should be able to get away with two mappings.  The keys can be the full, lowercase unit label,and the values can be "how we write on a graph", with a longhand and shorthand option.  However, this could/should stand-in for integration with Pint.  

It would be a good exercise to spend 2h reviewing Pint tutorials and give an estimate on
1. How nice it would be to have Pint()
2. How difficult it would be to integrate.

{"digital counts":"cts", 
"millivolts": "mV", 
"nanotesla": "nT", 
"tesla":  "T",
"volts": "V"}

{"digital counts": "digital counts",
"millivolts": "milliVolts",
"tesla":  "Tesla",
"nanotesla": "nanoTesla", 
"volts": "Volts"}

**Comment by kkappler** [comment]
Added mt_metadata/util/units.py as a place to start tracking all unit stuff.  91102d1..ef264cf
Once the lists of units mature we can revisit what the units should be like.
