### ISSUE TITLE
FAP and FIR  not landing in filter_list under Experiment() after cast from xml

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mt_metadata#32]
Working on branch fir_fap_filters

**Comment by kujaku11** [comment]
@kkappler Try using branch `fix_issues` I updated experiment to take in FAP and FIR filters.

**Comment by kujaku11** [comment]
@kkappler Can you add example stationxml's that have FAP and FIR filters to the data to the `fix_issues` branch

**Comment by kkappler** [comment]
@kujaku11 I added two files, one from parkfield with FIR and another one that Tim used to test the ability to embed a FAP.

**Comment by kkappler** [comment]
FIR is making it into the experiment.surveys[0].filter_list

@kkappler will check if/whynot these are being applied and comment here

**Comment by kkappler** [comment]
They are landing in the filter list
