### ISSUE TITLE
Unconventional StationXML

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mt_metadata#33]
Observed Issues:
1. sometimes magnetic field is identifed by channel code "T" rather than "F"
2. At least some historical station xml  files are returning units of Ampres and Tesla.  We need code to handle these cases and correct for them.  In particular, I think the Amperes reference is incorrect and the Tesla is contrary to our convention.  
We need to both identify/log/report these issues and add compensatory scaling factors to calibration.
3. Some dipoles are Q2, Q3 for horizontal, but mt_metadata expects Q1, Q2.  How to handle this?

Most likely solution would seem to be update the stationxml rather than the code ... let's agree if that is the path and then make a plan for executing

**Comment by kkappler** [comment]
I have added a one off script to clean up the non-conformant xml at the inventory stage before it goes into mt_metadata.

**Comment by kujaku11** [comment]
@kkappler Is there a date where the conventions changed.  For instance did FDSN update the channel codes some time and added the magnetic and electric channels to the current letter code?  Could we use the data of the metadata to use different channel code dictionaries?  If this is a one off, as Anna suggests maybe a simple workaround is fine.

**Comment by kkappler** [comment]
I really don't know.  I know that when I used the NCEDC data circa 2010, all magnetometers were archived with "T" code. ... and vertical electric dipoles were Q1.  I reached out to Doug Neuhauser at BSL to get some insight into this issue and no response.

**Comment by kkappler** [comment]
Jared has hacked around the "T" instead of "F" issue for magnetic channel code.
Karl's one off code is in iris_mt_scratch/sandbox/io_helpers/test_data.py
as def scan_network_for_nonconformity(inventory)

**Comment by kkappler** [comment]
I Propose to use the workaround methods and scripts to create a Parkfield/Hollister mth5 file that we commit to the repo for testing.  That specific file can be maintained.  The scripts that make it can serve as an example for how to make an mth5 from unconventional xml, but we probably don't want to support these odd duck files in general.

I'll plan to get Gary's synthetic data and the parkfield running through the pipeline and then close this issue.

**Comment by kujaku11** [comment]
@kkappler sounds like a good plan, I would put the StationXML file in mt_metadata/data/station_xml and we can make a script in mt_metadata to convert the StationXML into an Experiment.  And another script in MTH5 to make an MTH5 file or just have one script in MTH5.

**Comment by kujaku11** [comment]
PR #142 updates reading of StationXML and most of these issues should be fixed.  Closing on PR
