### ISSUE TITLE
MTPy MT() Object Review 

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mt_metadata#36]
Pull MTPy and take a look at the MT() object, and see how the Transfer Functions from Aurora will fit into this container and then review .

Focus on 
mtpy/core/mt.py

You will need to look at Tipper and Impedance Tensor.
Variances are stored right now, but the covariances are not.
** Covariances not stored right now.
Some say full covariances are needed todo the rotations for the errors.  This is arguable however.

This issue blocks issue #2

**Comment by kujaku11** [comment]
For now we will have all transfer functions read in by mt_metadata and passed to MTpy to plot.  Will close this issue for now.
