### ISSUE TITLE
Two Filter Plotting Functions should be merged into One

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mt_metadata#37]
At a minimum, put all filter plotters into a single module.  Remove redundancies.

<1>
mt_metadata/timeseries/filters/filter_base.py:140:from mt_metadata.timeseries.filters.plotting_helpers import plot_response
</1>

<2>
mt_metadata/timeseries/filters/filter_base.py:303:    def plot_complex_response(self, frequency_axis, **kwargs):
mt_metadata/timeseries/filters/filter_base.py:304:        from iris_mt_scratch.sandbox.plot_helpers import plot_complex_response
</2>

**Comment by kujaku11** [comment]
This has been done in filters, there is now a `plot_response` function that will plot the amplitude and phase and if poles and zeros are present, will plot those in a separate subplot as well.
