### ISSUE TITLE
Get up on PIP and Conda

### ISSUE THREAD

**Issue by kujaku11** [kujaku11/mt_metadata#4]
Build the infrastructure to get up onto PIP and Conda so that it can be installed easily.

**Comment by lheagy** [comment]
@kujaku11: do you have an account on the test pypi and pypi sites? 
- test: https://test.pypi.org/account/register/
- pypi: https://pypi.org/account/register/

Would you mind sharing those with me? (here or on slack is fine)

**Comment by kujaku11** [comment]
@lheagy Any chance you could bump the current version to 0.1.1.  I think there has been a good amount of development to warrant a bump.  I completed 2 PR's #19  and #29.  @kkappler agree?

**Comment by kkappler** [comment]
Go for it.  This seems to be partially blocked by some security issues on Jared's work machine ... how to get around this in general?

**Comment by lheagy** [comment]
It looks like 0.1.1 was released on May 12? https://github.com/kujaku11/mt_metadata/releases/tag/v0.1.1

should I bump to 0.1.2?

**Comment by kujaku11** [comment]
@lheagy Let's wait on the bump version release for a second, I want to pull updates into main and then we can release that as 0.1.1?

**Comment by kujaku11** [comment]
@lheagy We just did the pull request and all tests pass.  We can go ahead an release the main as either 0.1.1 or bump it to 0.1.2.

**Comment by lheagy** [comment]
sounds good -- I will get that done today

**Comment by brunorpinho** [comment]
PyPI is behind this repo so the package you get when you `pip install mt_metadata` doesn't play well with the rest of the ecosystem.
Temp fix:
```pip install git+https://github.com/kujaku11/mt_metadata.git```
