### ISSUE TITLE
Pass mth5 station_metadata to transfer_function_header

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mt_metadata#42]
Gary's transfer_function_header class contains station_header objects for local and remote sites.  We probably want to emulate this but let's take our "station_header" object to be an mth5 station metadata object.

**Comment by kkappler** [comment]
whoops, I meant to create this under aurora.  Not sure how to transfer the issue as I can't find the aurora repo when I push the "Transfer Issue" button at the bottom.  @lheagy  can we take a look at this on Wednesday time permitting?

**Comment by kujaku11** [comment]
@kkappler This can be a duplicate for Aurora but can reside here.  Suggest we add a metadata object, like Processing that would take in the objects that need to be passed from the timeseries to the transfer function:

- Station (`mt_metadata.timeseries.Station`) 
- Remote References list of `mt_metadata.timeseries.Station` objects
- Channels used, "runs" used, etc.
- Processing parameters

**Comment by kujaku11** [comment]
The metadata has been handled for this case to make a self describing transfer function.
