### ISSUE TITLE
Move pass_band() method higher in the class hierarchy

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mt_metadata#47]
We originally put this in the pole-zero filter, but this is a relevant thing to many filters.  It should either move into the base class, and/or factored into a helper function.

**Comment by kkappler** [comment]
While we are at it, let's review the intended significance of "normalization_frequency" method.

http://docs.fdsn.org/projects/stationxml/en/latest/reference.html#stagegain-required
In stationXML the stage gain and associated frequency are required.  So while we may want to estimate a normalization frequency for non-stationXML representations, we may wish to override this method with the value from the xml for IRIS data.

**Comment by kujaku11** [comment]
A `pass_band` attribute has been added to all filters and the `normalization_frequency` is estimated based on the `pass_band`.
