### ISSUE TITLE
Create Filters XML Reader 

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mt_metadata#5]
We need one.
migrate /mth5/examples/filter_prototyping.py into metadata repository and make it read filters.xml

**Comment by kujaku11** [comment]
Good thought.  I guess there are 2 things.  

1. How should we split the difference between the filter metadata and filter data? Or should there be a difference?
2. Obspy should be the reader for a StationXML filter then we need to translate that into mt filter.  So is the current status of mt_filter metadata comprehensive enough to hold any filter?

**Comment by kkappler** [comment]
We are creating filters from station XML
