### ISSUE TITLE
Translation of MT metadata to StationXML is not quite right yet.

### ISSUE THREAD

**Issue by kujaku11** [kujaku11/mt_metadata#64]
- The order of the runs is should be alphabetic or numeric, currently random. Probably has to do with how the runs are collected.
- Survey:
    - Missing: `survey.id`, `operator.contact`
- Channel:
    - Missing `latitude`, `longitude`, `elevation` values, which seem to be filled from the station metadata.  
    - `calibration_units` should be physical units     

@akelbert Can you find any other issues?

**Comment by akelbert** [comment]
@kujaku11 yes, also:

- The order of Channels should be Hx,Hy,Hz,Ex,Ey (currently random)
- Need to encode analog Coefficient filters as PolesZeros with a StageGain
- Units "Name" should use standard abbreviations (e.g., nT etc)
- Station iris:alternateNetworkCodes is a missing attribute
- Equipment.Description is written out randomly (not alphabetically)
- Magnetic Response.InstrumentSensitivity.Value - why 100.905? Should be 100.0 (1 nT = 100 counts)
- Missing elements: 

1. Operator.Contact
2. Site.Country
3. Sensor.Description

The Coefficient filters issue is the most important - it won't pass the validation (as currently supported) unless that's done. Also, I've now rearranged the filters in order: electric_si_units, electric_si_units_to_voltage, electric_butterworth_low_pass, electric_butterworth_high_pass, electric_analog_to_digital, electric_time_offset (as discussed and agreed on the last call).

I will complete the changed that we discussed and start rearchiving with my Matlab code for now.

**Comment by kujaku11** [comment]
@akelbert 

- [x] The order of Channels should be Hx,Hy,Hz,Ex,Ey (currently random) 
- [ ] Need to encode analog Coefficient filters as PolesZeros with a StageGain
    - I don't think this is a bug, if that's the way we need to encode it then the input should be a `PoleZeroFilter` with a gain.   It would be too complicated to sometimes convert to a `CoefficientFilter` and sometimes to a `PoleZeroFilter` 
- [x] Units "Name" should use standard abbreviations (e.g., nT etc)
- [ ] Station iris:alternateNetworkCodes is a missing attribute
      - This is not currently an option using Obspy.  We can add `station.fdsn.alternate_network_code` as a place to store the information and we can write a workaround to add that information in.     
- [ ] Equipment.Description is written out randomly (not alphabetically)
    - Not sure what the problem here is?  Is it that the equipment description is written alphabetically using `mt_metadata`?  Don't see what the order has to do with anything they are key=value pairs and should be easily parsed.  
- [x] Magnetic Response.InstrumentSensitivity.Value - why 100.905? Should be 100.0 (1 nT = 100 counts)
    - With the other filters gain included the full response in the pass band (> .1s) is 100.905.  Since StationXML asks for the full sensitivity in the pass band this is the number provide.  See the plot of the full response for a magnetic channel in the pass band.   ![mag_response](https://user-images.githubusercontent.com/2100870/139963523-4c6b7498-2c01-47b0-8918-b4fb49fa71b3.png)
- [ ] The channels have a `latitude`, `longitude`, and `elevation` these are pulled from the channel metadata:
    - `Electric` gets the location from `Electric.positive.latitude`, `Electric.positive.longitude`, `Electric.positive.elevation`, therefore these need to be filled if the channel location is going to be filled in a StationXML
    - `Magnetic` and `Auxiliary` gets filled from `Channel.location.latitude`,  `Channel.location.longitude`, `Channel.location.elevation`, therefore these need to be filled if the channel location is going to be filled in a StationXML
    - I wrote in a test if the locations are 0 then use the station location.   
- [x] Missing elements: 
    - [x] Operator.Contact
    - [x] Site.Country
    - [x] Sensor.Description

I have updated these in a new pull request and should be on the main branch tomorrow.

**Comment by akelbert** [comment]
@kujaku11 cool, thanks! All makes sense, mostly. 

Re: Equipment.Description, not an issue except insofar as on comparison between my codes and yours we wish to eliminate unnecessary differences.

Re: Response.InstrumentSensitivity.Value, I'm not an engineer and might need to be guided here a little. Are you saying that the correct conversion is not 1 nT = 100 count but 1 nT = 100.905 counts? Is that number inherent to the instrument? Should the gain be adjusted as well? It is possible that the digitizer is the same as for the electrics, with the gain of 4.0960e+08, but I understood from Gary that NIMS were calibrated in such a way that 1 nT = 100 count in the end; was that an approximation?

Re: the PolesZeros filter vs Coefficient filter, I agree with your logic but recording these appropriately in StationXML would be a relatively easy and generic solution. Specifically, if the output units are anything but count (i.e., analog) than code it up as PolesZeros, otherwise (analog to digital, or digital) use Coefficients. Since this logic is inherent to StationXML, I believe that it belongs in the converter. I can, of course, adapt the filters on the input but I don't think that's appropriate in general.

Second (similar!) question regards the dipole length multiplication - the options are to make it a more general filter ("variable coefficient", then pull from the dipole length value) which would make the conversion more complicated, or make the filters complicated and the conversion simpler. 

I guess these two go back to different coding philosophies. I find that the most common cause of problems is human error, so I try to reduce the possibility for human error by making things simpler on the end of humans. Conversion tools only require some extra coding once, and that coding is then used over and over by allowing for simpler inputs. 

These two little extensions are done in Matlab on my end. Too bad I'm not a python coder and don't have spare time on my hands to implement these features on your end as well. Maybe someone will. It would be really nice to make the tools compatible!

**Comment by kujaku11** [comment]
@akelbert 

> Re: Response.InstrumentSensitivity.Value, I'm not an engineer and might need to be guided here a little. Are you saying that the correct conversion is not 1 nT = 100 count but 1 nT = 100.905 counts? Is that number inherent to the instrument? Should the gain be adjusted as well? It is possible that the digitizer is the same as for the electrics, with the gain of 4.0960e+08, but I understood from Gary that NIMS were calibrated in such a way that 1 nT = 100 count in the end; was that an approximation?

It would appear that 100 is an approximation, at least from how the filters are represented, now the filters could be slightly off.  @kkappler could you shed some light on this small discrepency between the filter sensitivity being 100.905 counts per nT?  Do you think its correct?  It could be the filters, cause I'm guessing the digitizer is the same as the electric channels and that has been lumped into stage 1, so the normalization factor could be slightly off if we think 100 is the correct sensitivity.  

> Re: the PolesZeros filter vs Coefficient filter, I agree with your logic but recording these appropriately in StationXML would be a relatively easy and generic solution. Specifically, if the output units are anything but count (i.e., analog) than code it up as PolesZeros, otherwise (analog to digital, or digital) use Coefficients. Since this logic is inherent to StationXML, I believe that it belongs in the converter. I can, of course, adapt the filters on the input but I don't think that's appropriate in general.
> 
> Second (similar!) question regards the dipole length multiplication - the options are to make it a more general filter ("variable coefficient", then pull from the dipole length value) which would make the conversion more complicated, or make the filters complicated and the conversion simpler. 

I've incorporated both of these into the code in pull request #65.  

1. As you say if the units of a coefficient filter are not counts then a `PoleZeroFilter` is created with empty poles and zeros and just a gain. This is only when translating to an StationXML filter stage.  I still have to write logic for the reverse.   
2. In the MT2StationXML I added logic that if a dipole length filter is in the `filter.name` list a `PoleZeroFilter` is created with the gain being the dipole length of that channel and the filter is renamed `dipole_##.###m` this will reduce any repeat filters.  I still think this is a use case specific to how you create the filters so we will leave it in the MT2StationXML function, I don't think we need to create a new filter type, it creates complicated lookup logic.

I have to make sure all the tests run but will be pushing to `main` soon.

**Comment by kujaku11** [comment]
@timronan Looks like StationXML produced from an IRIS request are different in that some of the comments repeat at the network level.  Its and xml, had to change the extension to txt. Have a look.

[v1_make_mth5.txt](https://github.com/kujaku11/mt_metadata/files/8498345/v1_make_mth5.txt)

**Comment by timronan** [comment]
I see the duplication: The network information is normally handled manually so I need to track this bug down. 

http://service.iris.edu/fdsnws/station/1/query?net=8P&starttime=2019-01-01T00:00:00&level=network&format=xml&includecomments=true&nodata=404

**Comment by timronan** [comment]
@kujaku11 I updated the metadata for CAS04, NVR08, CAV07,  NVR11, REV06. 

Let me know if you see any issues. 

These data are available at: 


[CAS04] http://service.iris.edu/fdsnws/station/1/query?net=8P&sta=CAS04&starttime=2019-01-01T00:00:00&level=channel&format=xml&includecomments=true&nodata=404

[NVR08] http://service.iris.edu/fdsnws/station/1/query?net=8P&sta=NVR08&starttime=2019-01-01T00:00:00&level=channel&format=xml&includecomments=true&nodata=404

[NVR011] http://service.iris.edu/fdsnws/station/1/query?net=8P&sta=NVR11&starttime=2019-01-01T00:00:00&level=channel&format=xml&includecomments=true&nodata=404

[CAV07] http://service.iris.edu/fdsnws/station/1/query?net=8P&sta=CAV07&starttime=2019-01-01T00:00:00&level=channel&format=xml&includecomments=true&nodata=404

[REV06] http://service.iris.edu/fdsnws/station/1/query?net=8P&sta=REV06&starttime=2019-01-01T00:00:00&level=channel&format=xml&includecomments=true&nodata=404

**Comment by kujaku11** [comment]
With wide scale testing done by @kkappler this has been ironed out and nearly all stationXML files on IRIS can now be read in. Writing has not been fully tested, but closing for now.
