### ISSUE TITLE
When Units are None?

### ISSUE THREAD

**Issue by kujaku11** [kujaku11/mt_metadata#68]
@kkappler, @timronan

When `input_units` and `output_units` are None an error was thrown because a `None` unit was not defined.

I updated the code to allow `None` as an input, it returns all `unknown` values for the unit object.  I also added a key word argument to `mt_metadata.utils.units.get_unit_object(value, allow_none=True)`.  This may be a hack since we should probably force the user to input units.  We could set `allow_none=False` by default which would raise a `KeyError` or we could have it raise a `ValueError`.  

Which do you think it should be.  To keep tests passing we should keep it set to `True`, but in the future we could switch it to `False`

It would seem like the older StationXML files on EM do not have the units in them.

**Comment by timronan** [comment]
@kujaku11 this seem like a good work around for the problem. It is good that a value, Unknown, is assigned to the units in the MT metadata unit object. 

Input and output unit are required for both the Dataless Seed and Stationxml schemas.  Saying this, there are probably some older metadata that are missing units, so it is useful to have this flag for conversion proposes. It will allow us to normalize the historical MT archive to a modern standard.

**Comment by kkappler** [comment]
I agree.  Let's set to True to keep tests passing and it can be something that is set to False by default for a later release.  An issue can be added in aurora to run tests with this set to False to flush out any datasets / cases with undefined units in future.

**Comment by kujaku11** [comment]
Ok, for now `unknown` units are allowed.  Will close this for now, but can be reopened in the future.
