### ISSUE TITLE
Possibly Inconsistent Standards for IGRF label

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mt_metadata#78]
Running some test runs of aurora and I encounter the following error after the TF is computed:
```
~/software/irismt/mt_metadata/mt_metadata/base/metadata.py in __setattr__(self, name, value)
    339                     if not accept:
    340                         self.logger.error(msg.format(value, options))
--> 341                         raise MTSchemaError(msg.format(value, options))
    342                     if other and not accept:
    343                         self.logger.warning(msg.format(value, options, name))

MTSchemaError: IGRF-13 not found in options list ['EMAG2', 'EMM', 'HDGM', 'IGRF', 'WMM', 'unknown']
```

A scan of the mt_metadata codebase for the string IGRF shows that it only occurs in the form "IGRF-13" in .py files, but occurs as "IGRF" in some json standards files.

@kujaku11 Can you check if this is expected behaviour? I am running these tests locally on _main_ branch.

```
(base) kkappler@thales4:~/software/irismt$ rgreppy IGRF
mt_metadata/tests/timeseries/stationxml/test_station.py:137:        self.assertEqual(self.mt_station.location.declination.model, "IGRF-13")
(base) kkappler@thales4:~/software/irismt$ rgrepjson IGRF
mt_metadata/mt_metadata/transfer_functions/tf/standards/declination.json:23:            "IGRF",
mt_metadata/mt_metadata/timeseries/standards/declination.json:24:            "IGRF",

```

**Comment by kujaku11** [comment]
@kkappler Good catch, I think how it is meant to be is that there is a:

`location.declination.model = IGRF`
'location.declination.epoch` = 2013`

for `IGRF-13`.

I'll try to update the documentation on this.  This may not be the standard way to record a declination model?

**Comment by kujaku11** [comment]
@kkappler Added "other" to the standards which will allow for IGRF-13 in the transfer function metadata.  You were right there was inconsistency between timeseries and transfer function metadata.  This fix with provide consistency.  Merged into `main`
